# --- DEPLOYMENT (The Application) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-service
spec:
  replicas: 1 # Run 1 copy of the app
  selector:
    matchLabels:
      app: link-service
  template:
    metadata:
      labels:
        app: link-service
    spec:

      imagePullSecrets:
        - name: regcred
      containers:
        - name: link-service


          image: 408834627625.dkr.ecr.ap-south-1.amazonaws.com/link-service:c18baedb8dbe1dfecfca1b2b89283d5c1a3df754
          ports:
            - containerPort: 8080
          env:

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://linkhub-db-prod.cboc8ogyqde1.ap-south-1.rds.amazonaws.com:5432/linkhub" # Note: pointing to a future K8s service
            - name: SPRING_DATASOURCE_USERNAME
              value: "linkhub"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"



---
# --- SERVICE
apiVersion: v1
kind: Service
metadata:
  name: link-service
spec:
  selector:
    app: link-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP